version: "3.7"
services:
  funasronline:
    image: asr:latest
    container_name: funasronline
    restart: always
    privileged: true
    networks:
      - asrnet
    ports:
      - 10095:10095
    volumes:
      - "./funasr-runtime-resources/models:/workspace/models"

networks:
  asrnet:
    driver: bridge